# Generated by scripts/gen-craft-casks.py from scripts/craft-casks.json — edit
# those, not this file. CI re-renders every Craft cask and fails on any drift.
cask "filmcraft-linux" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.5.0"
  sha256 arm64_linux:  "b1c75878e91c80c62faabff8b617dcd41ff25a09ec43c4745f125caf699620c4",
         x86_64_linux: "be2183f9859c013cbf2e8dc29524532503a3eb75e2156af617bd4df7ffad40dd"

  url "https://github.com/storytold/filmcraft/releases/download/v#{version}/filmcraft-#{version}-linux-#{arch}.tar.gz"
  name "FilmCraft"
  desc "Premiere-style video editor"
  homepage "https://getartcraft.com/apps/filmcraft"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Why: upstream's macOS build is a separate .dmg, which belongs in the
  # official homebrew/cask cask of the same name, not here. This tarball is
  # Linux ELF, so refuse to install anywhere else.
  depends_on linux: :any

  # Why both: the first is the GUI and the second is upstream's headless
  # command-line and MCP front end to the same engine, under the names the .deb
  # and .rpm install to /usr/bin.
  binary "filmcraft-#{version}-linux-#{arch}/bin/filmcraft"
  binary "filmcraft-#{version}-linux-#{arch}/bin/filmcraft-cli"
  # Why upstream's reverse-DNS file names are kept: on Wayland the compositor
  # finds a window's launcher, and so its dock icon, by matching the window's
  # app_id against the installed .desktop file's name.
  artifact "filmcraft-#{version}-linux-#{arch}/share/applications/ai.storyteller.filmcraft.desktop",
           target: "#{Dir.home}/.local/share/applications/ai.storyteller.filmcraft.desktop"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/128x128/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/128x128/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/16x16/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/16x16/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/24x24/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/24x24/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/256x256/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/256x256/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/32x32/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/32x32/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/48x48/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/48x48/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/512x512/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/512x512/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/64x64/apps/ai.storyteller.filmcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/64x64/apps/ai.storyteller.filmcraft.png"
  artifact "filmcraft-#{version}-linux-#{arch}/share/icons/hicolor/scalable/apps/ai.storyteller.filmcraft.svg",
           target: "#{Dir.home}/.local/share/icons/hicolor/scalable/apps/ai.storyteller.filmcraft.svg"
  artifact "filmcraft-#{version}-linux-#{arch}/share/mime/packages/ai.storyteller.filmcraft.xml",
           target: "#{Dir.home}/.local/share/mime/packages/ai.storyteller.filmcraft.xml"

  preflight_steps do
    # Why: upstream's entry runs the bare binary name and relies on the
    # session's PATH, which on a desktop usually lacks the Homebrew prefix — only
    # login shells that source brew's shellenv have it. Pointing Exec at the bin symlink keeps the
    # entry working across upgrades and keeps upstream's own arguments (%F).
    # No `audit_result: false`: an entry with no Exec line is a broken payload.
    inreplace "filmcraft-{{version}}-linux-{{arch}}/share/applications/ai.storyteller.filmcraft.desktop",
              /^Exec=\S+/,
              "Exec={{HOMEBREW_PREFIX}}/bin/filmcraft"
    # Why TryExec too: a TryExec the shell cannot resolve hides the entry
    # outright, so leaving it bare would undo the Exec fix above. Not every app
    # sets one, hence `audit_result: false`.
    inreplace "filmcraft-{{version}}-linux-{{arch}}/share/applications/ai.storyteller.filmcraft.desktop",
              /^TryExec=.*$/,
              "TryExec={{HOMEBREW_PREFIX}}/bin/filmcraft",
              audit_result: false
  end

  # Why: without a refresh the launcher, its icon and the file associations only
  # appear after the next login. `must_succeed: false` keeps each step a no-op
  # on desktops that do not ship the tool.
  #
  # The paths are spelled out with `{{user}}` rather than `~` because these
  # steps run in Homebrew's cask sandbox, whose $HOME is an empty directory, and
  # `writable_paths` with `writable_base: :home` is what lets them write to the
  # real one. This is the same pattern every other desktop cask in this tap
  # uses; see paseo-linux.rb for the long version.
  postflight_steps do
    run "update-desktop-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/applications",
        writable_paths: [".local/share/applications"],
        writable_base:  :home,
        must_succeed:   false
    run "gtk-update-icon-cache",
        args:           ["-f", "-t", "."],
        chdir:          "/home/{{user}}/.local/share/icons/hicolor",
        writable_paths: [".local/share/icons/hicolor"],
        writable_base:  :home,
        must_succeed:   false
    run "update-mime-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/mime",
        writable_paths: [".local/share/mime"],
        writable_base:  :home,
        must_succeed:   false
  end

  uninstall_postflight_steps do
    run "update-desktop-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/applications",
        writable_paths: [".local/share/applications"],
        writable_base:  :home,
        must_succeed:   false
    run "gtk-update-icon-cache",
        args:           ["-f", "-t", "."],
        chdir:          "/home/{{user}}/.local/share/icons/hicolor",
        writable_paths: [".local/share/icons/hicolor"],
        writable_base:  :home,
        must_succeed:   false
    run "update-mime-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/mime",
        writable_paths: [".local/share/mime"],
        writable_base:  :home,
        must_succeed:   false
  end

  zap trash: "~/.local/share/filmcraft"

  caveats <<~EOS
    Homebrew owns this install's version. Upgrade with:
      brew upgrade --cask filmcraft-linux

    `filmcraft` is the GUI and `filmcraft-cli` its command-line and MCP front end.
    The CLI needs nothing beyond glibc. The GUI loads its windowing and
    graphics stack at run time — Wayland or X11, libxkbcommon, and Vulkan or
    EGL — which any desktop session already has and Homebrew cannot supply.

    If you have run upstream's AppImage, it registered its own launcher and
    icons under ~/.local/share/applications and ~/.local/share/icons, and this
    install will refuse to overwrite them. Reinstall with --force to take them
    over.
  EOS
end
