# Generated by scripts/gen-craft-casks.py from scripts/craft-casks.json — edit
# those, not this file. CI re-renders every Craft cask and fails on any drift.
cask "gridcraft-linux" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.4.0"
  sha256 arm64_linux:  "a6ff25f28d81f206fc85cb718b251fda77df8fe7ed12673c3645b91fd301a616",
         x86_64_linux: "d24f39e65affaf5b18ebf2a423ef12f05431b6d236a8b13457e7bf58e328309c"

  url "https://github.com/storytold/gridcraft/releases/download/v#{version}/gridcraft-#{version}-linux-#{arch}.tar.gz"
  name "GridCraft"
  desc "Microsoft Excel-style spreadsheet"
  homepage "https://github.com/storytold/gridcraft"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Why: upstream's macOS build is a separate .dmg, which belongs in the
  # official homebrew/cask cask of the same name, not here. This tarball is
  # Linux ELF, so refuse to install anywhere else.
  depends_on linux: :any

  # Why both: the first is the GUI and the second is upstream's headless
  # command-line and MCP front end to the same engine, under the names the .deb
  # and .rpm install to /usr/bin.
  binary "gridcraft-#{version}-linux-#{arch}/bin/gridcraft"
  binary "gridcraft-#{version}-linux-#{arch}/bin/gridcraft-cli"
  # Why upstream's reverse-DNS file names are kept: on Wayland the compositor
  # finds a window's launcher, and so its dock icon, by matching the window's
  # app_id against the installed .desktop file's name.
  artifact "gridcraft-#{version}-linux-#{arch}/share/applications/ai.storyteller.gridcraft.desktop",
           target: "#{Dir.home}/.local/share/applications/ai.storyteller.gridcraft.desktop"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/128x128/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/128x128/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/16x16/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/16x16/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/24x24/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/24x24/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/256x256/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/256x256/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/32x32/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/32x32/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/48x48/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/48x48/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/512x512/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/512x512/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/64x64/apps/ai.storyteller.gridcraft.png",
           target: "#{Dir.home}/.local/share/icons/hicolor/64x64/apps/ai.storyteller.gridcraft.png"
  artifact "gridcraft-#{version}-linux-#{arch}/share/icons/hicolor/scalable/apps/ai.storyteller.gridcraft.svg",
           target: "#{Dir.home}/.local/share/icons/hicolor/scalable/apps/ai.storyteller.gridcraft.svg"
  artifact "gridcraft-#{version}-linux-#{arch}/share/mime/packages/ai.storyteller.gridcraft.xml",
           target: "#{Dir.home}/.local/share/mime/packages/ai.storyteller.gridcraft.xml"

  preflight_steps do
    # Why: upstream's entry runs the bare binary name and relies on the
    # session's PATH, which on a desktop usually lacks the Homebrew prefix — only
    # login shells that source brew's shellenv have it. Pointing Exec at the bin symlink keeps the
    # entry working across upgrades and keeps upstream's own arguments (%F).
    # No `audit_result: false`: an entry with no Exec line is a broken payload.
    inreplace "gridcraft-{{version}}-linux-{{arch}}/share/applications/ai.storyteller.gridcraft.desktop",
              /^Exec=\S+/,
              "Exec={{HOMEBREW_PREFIX}}/bin/gridcraft"
    # Why TryExec too: a TryExec the shell cannot resolve hides the entry
    # outright, so leaving it bare would undo the Exec fix above. Not every app
    # sets one, hence `audit_result: false`.
    inreplace "gridcraft-{{version}}-linux-{{arch}}/share/applications/ai.storyteller.gridcraft.desktop",
              /^TryExec=.*$/,
              "TryExec={{HOMEBREW_PREFIX}}/bin/gridcraft",
              audit_result: false
  end

  # Why: without a refresh the launcher, its icon and the file associations only
  # appear after the next login. `must_succeed: false` keeps each step a no-op
  # on desktops that do not ship the tool.
  #
  # The paths are spelled out with `{{user}}` rather than `~` because these
  # steps run in Homebrew's cask sandbox, whose $HOME is an empty directory, and
  # `writable_paths` with `writable_base: :home` is what lets them write to the
  # real one. This is the same pattern every other desktop cask in this tap
  # uses; see paseo-linux.rb for the long version.
  postflight_steps do
    run "update-desktop-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/applications",
        writable_paths: [".local/share/applications"],
        writable_base:  :home,
        must_succeed:   false
    run "gtk-update-icon-cache",
        args:           ["-f", "-t", "."],
        chdir:          "/home/{{user}}/.local/share/icons/hicolor",
        writable_paths: [".local/share/icons/hicolor"],
        writable_base:  :home,
        must_succeed:   false
    run "update-mime-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/mime",
        writable_paths: [".local/share/mime"],
        writable_base:  :home,
        must_succeed:   false
  end

  uninstall_postflight_steps do
    run "update-desktop-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/applications",
        writable_paths: [".local/share/applications"],
        writable_base:  :home,
        must_succeed:   false
    run "gtk-update-icon-cache",
        args:           ["-f", "-t", "."],
        chdir:          "/home/{{user}}/.local/share/icons/hicolor",
        writable_paths: [".local/share/icons/hicolor"],
        writable_base:  :home,
        must_succeed:   false
    run "update-mime-database",
        args:           ["."],
        chdir:          "/home/{{user}}/.local/share/mime",
        writable_paths: [".local/share/mime"],
        writable_base:  :home,
        must_succeed:   false
  end

  zap trash: "~/.config/gridcraft"

  caveats <<~EOS
    Homebrew owns this install's version. Upgrade with:
      brew upgrade --cask gridcraft-linux

    `gridcraft` is the GUI and `gridcraft-cli` its command-line and MCP front end.
    The CLI needs nothing beyond glibc. The GUI loads its windowing and
    graphics stack at run time — Wayland or X11, libxkbcommon, and Vulkan or
    EGL — which any desktop session already has and Homebrew cannot supply.

    If you have run upstream's AppImage, it registered its own launcher and
    icons under ~/.local/share/applications and ~/.local/share/icons, and this
    install will refuse to overwrite them. Reinstall with --force to take them
    over.
  EOS
end
