# Auto-generated by crw-brew from upstream's GitHub releases.
# Do not edit by hand — run `update.sh` (CI keeps it current).
class Crw < Formula
  desc "Turn URLs into clean markdown or JSON — scrape, crawl, search, MCP server"
  homepage "https://github.com/us/crw"
  version "0.37.0"
  # Upstream declares the deprecated bare "AGPL-3.0" and ships AGPLv3 with no
  # "or later" clause, which is SPDX "AGPL-3.0-only".
  license "AGPL-3.0-only"

  # Prebuilt x86_64 Linux bottle so `brew install` pours it with no C compiler
  # (Homebrew-on-Linux otherwise requires one — a problem on atomic distros).
  # macOS and other arches fall back to the upstream url below; macOS always has
  # clang via the required Command Line Tools, so no bottle is needed.
  bottle do
    root_url "https://github.com/jakobhviid/crw-brew/releases/download/v0.37.0"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "90dbd7d8ff3406c0493cf3d06d6f87330a77c894c68e1d931584c31b381e69c0"
  end

  on_macos do
    on_arm do
      url "https://github.com/us/crw/releases/download/v0.37.0/crw-darwin-arm64.tar.gz"
      sha256 "9d8cc0ac84af237e054424ddbc4f2ef822cfb33301b2c20e5664fdf9fabd6a53"
    end
    on_intel do
      url "https://github.com/us/crw/releases/download/v0.37.0/crw-darwin-x64.tar.gz"
      sha256 "5230b7d6cf9c870a14e2ed142375e3bd4cd9234061f24f340706dee84f1d2e4f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/us/crw/releases/download/v0.37.0/crw-linux-arm64.tar.gz"
      sha256 "5f7daa5fb760f2c6ee17c872916697f47e2622a1d44a6b8b46fceb3d765d5689"
    end
    on_intel do
      url "https://github.com/us/crw/releases/download/v0.37.0/crw-linux-x64.tar.gz"
      sha256 "53a04dc3712706811e49a86fca6dddf46ca3c580ebaab69e93139825e7686df9"
    end
  end

  def install
    bin.install "crw"
  end

  def caveats
    <<~EOS
      crw runs fully locally — no account, no API key:

        crw example.com                 # page as markdown on stdout
        crw mcp                         # embedded MCP server for AI agents
        crw doctor                      # check renderer, search, proxy, ports

      When a page returns thin content, crw escalates to its own JS renderer and
      says so on stderr. Sites behind a Cloudflare challenge or DataDome return
      the interstitial rather than the article — clearing those needs a real
      browser session, not a renderer.

      `crw search` needs a backend: either a local one or the hosted CRW Cloud
      via `crw setup` (paid, with a free credit allowance). Scraping, crawling,
      mapping and the MCP server need none of it.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crw --version")
  end
end
