# Auto-generated by crw-brew from upstream's GitHub releases.
# Do not edit by hand — run `update.sh` (CI keeps it current).
class Crw < Formula
  desc "Turn URLs into clean markdown or JSON — scrape, crawl, search, MCP server"
  homepage "https://github.com/us/crw"
  version "0.35.1"
  # Upstream declares the deprecated bare "AGPL-3.0" and ships AGPLv3 with no
  # "or later" clause, which is SPDX "AGPL-3.0-only".
  license "AGPL-3.0-only"

  # Prebuilt x86_64 Linux bottle so `brew install` pours it with no C compiler
  # (Homebrew-on-Linux otherwise requires one — a problem on atomic distros).
  # macOS and other arches fall back to the upstream url below; macOS always has
  # clang via the required Command Line Tools, so no bottle is needed.
  bottle do
    root_url "https://github.com/jakobhviid/crw-brew/releases/download/v0.35.1"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "20aeb14e013801625b3a4e88691d842797fb80e51508d2268414be73095dc480"
  end

  on_macos do
    on_arm do
      url "https://github.com/us/crw/releases/download/v0.35.1/crw-darwin-arm64.tar.gz"
      sha256 "0f7be68bb42f94984f7b4d825495af7a6f603d73a947a8e8924298c4bf96a272"
    end
    on_intel do
      url "https://github.com/us/crw/releases/download/v0.35.1/crw-darwin-x64.tar.gz"
      sha256 "3f53bd39328696ce8e59741b3b461bc6f1829f4f73b9a9de7afcea3e81ad5205"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/us/crw/releases/download/v0.35.1/crw-linux-arm64.tar.gz"
      sha256 "3aa64e6dbc710b6e4a26c6b778d74d926cfadb01d691d9a127b16c78a040351d"
    end
    on_intel do
      url "https://github.com/us/crw/releases/download/v0.35.1/crw-linux-x64.tar.gz"
      sha256 "7b18059cb9e5586ed3fdfcc86097942d10860f687e840a0df5f818182954a2a9"
    end
  end

  def install
    bin.install "crw"
  end

  def caveats
    <<~EOS
      crw runs fully locally — no account, no API key:

        crw example.com                 # page as markdown on stdout
        crw mcp                         # embedded MCP server for AI agents
        crw doctor                      # check renderer, search, proxy, ports

      When a page returns thin content, crw escalates to its own JS renderer and
      says so on stderr. Sites behind a Cloudflare challenge or DataDome return
      the interstitial rather than the article — clearing those needs a real
      browser session, not a renderer.

      `crw search` needs a backend: either a local one or the hosted CRW Cloud
      via `crw setup` (paid, with a free credit allowance). Scraping, crawling,
      mapping and the MCP server need none of it.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crw --version")
  end
end
