# Auto-generated by crw-brew from upstream's GitHub releases.
# Do not edit by hand — run `update.sh` (CI keeps it current).
class Crw < Formula
  desc "Turn URLs into clean markdown or JSON — scrape, crawl, search, MCP server"
  homepage "https://github.com/us/crw"
  version "0.33.0"
  # Upstream declares the deprecated bare "AGPL-3.0" and ships AGPLv3 with no
  # "or later" clause, which is SPDX "AGPL-3.0-only".
  license "AGPL-3.0-only"

  # Prebuilt x86_64 Linux bottle so `brew install` pours it with no C compiler
  # (Homebrew-on-Linux otherwise requires one — a problem on atomic distros).
  # macOS and other arches fall back to the upstream url below; macOS always has
  # clang via the required Command Line Tools, so no bottle is needed.
  bottle do
    root_url "https://github.com/jakobhviid/crw-brew/releases/download/v0.33.0"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "0da8f29a344acd0c753257aee6e44c082523b8a7e6f5cd1d243d813ab5bca759"
  end

  on_macos do
    on_arm do
      url "https://github.com/us/crw/releases/download/v0.33.0/crw-darwin-arm64.tar.gz"
      sha256 "d5340480725e63b09b7046a78ffb9e4d27922b27a228f11b12c3df33e69bad7c"
    end
    on_intel do
      url "https://github.com/us/crw/releases/download/v0.33.0/crw-darwin-x64.tar.gz"
      sha256 "cd9b75e89ebeaffd69f728bc4965bc459386aa1c2f7daf611cc3f8e026abac72"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/us/crw/releases/download/v0.33.0/crw-linux-arm64.tar.gz"
      sha256 "b75d12159fdeeff121e226a2df8dec122adffa88161ee039db90cf1c42f34a98"
    end
    on_intel do
      url "https://github.com/us/crw/releases/download/v0.33.0/crw-linux-x64.tar.gz"
      sha256 "f29091aadd2a8b18f0712ed6bb484ae899c2e7f297bab55a6368f2fe73544b10"
    end
  end

  def install
    bin.install "crw"
  end

  def caveats
    <<~EOS
      crw runs fully locally — no account, no API key:

        crw example.com                 # page as markdown on stdout
        crw mcp                         # embedded MCP server for AI agents
        crw doctor                      # check renderer, search, proxy, ports

      When a page returns thin content, crw escalates to its own JS renderer and
      says so on stderr. Sites behind a Cloudflare challenge or DataDome return
      the interstitial rather than the article — clearing those needs a real
      browser session, not a renderer.

      `crw search` needs a backend: either a local one or the hosted CRW Cloud
      via `crw setup` (paid, with a free credit allowance). Scraping, crawling,
      mapping and the MCP server need none of it.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crw --version")
  end
end
