# Auto-generated by proton-drive-cli-brew from Proton's release manifest.
# Do not edit by hand — run `update.sh` (CI keeps it current).
class ProtonDriveCli < Formula
  desc "Access Proton Drive end-to-end encrypted cloud storage from the terminal"
  homepage "https://proton.me/drive"
  version "0.8.0"
  license "MIT"

  # Prebuilt x86_64 Linux bottle so `brew install` pours it with no C compiler
  # (Homebrew-on-Linux otherwise requires one — a problem on atomic distros).
  # macOS and other arches fall back to the direct-from-Proton url below; macOS
  # always has clang via the required Command Line Tools, so no bottle is needed.
  bottle do
    root_url "https://github.com/jakobhviid/proton-drive-cli-brew/releases/download/v0.8.0"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "a7cef02237918284d50c684b9e73b280e258cda68b8af3fce5d04dd1e34da87c"
  end

  on_macos do
    on_arm do
      url "https://proton.me/download/drive/cli/0.8.0/darwin-arm64/proton-drive"
      sha256 "dc8fc14de9ef07fcef28fe204051bb6729c49cf579170c8ce1ad669a26769711"
    end
    on_intel do
      url "https://proton.me/download/drive/cli/0.8.0/darwin-x64/proton-drive"
      sha256 "ba4c9d713755c4491282b418fc0115afc6aaeb01675bde19cc0a62c4833b6007"
    end
  end

  on_linux do
    # On a headless Linux server there's no Secret Service/libsecret keyring, so
    # the session can be stored in `pass` instead (PROTON_DRIVE_CREDENTIALS_STORE
    # — see caveats). Ship it so that path is one env var away, not another install.
    depends_on "pass"

    on_arm do
      url "https://proton.me/download/drive/cli/0.8.0/linux-arm64/proton-drive"
      sha256 "086bc4740a73cb8eb4900d51836bff0c332dda390b3f0780d9f805fd5c2a5fe3"
    end
    on_intel do
      url "https://proton.me/download/drive/cli/0.8.0/linux-x64/proton-drive"
      sha256 "9443d771719c892790db17e6f02ecd99ad7c53593329f3a67c77677dce577735"
    end
  end

  # Proton names the binary `proton-drive`; keep that so their docs' commands
  # work verbatim. The *formula* is proton-drive-cli to avoid the main app's name.
  def install
    bin.install "proton-drive"
  end

  def caveats
    <<~EOS
      proton-drive keeps its login session in your OS keyring — Keychain on macOS,
      Secret Service/libsecret on Linux. A headless Linux server has no keyring, so
      store the session in `pass` (installed as a dependency here) instead:

        gpg --quick-generate-key "proton-drive" default default never
        pass init "proton-drive"
        export PROTON_DRIVE_CREDENTIALS_STORE=pass   # add to your profile / systemd unit

      Sign-in is browser-based, so authenticate once interactively (or on a desktop
      sharing the same pass/GPG key) — then unattended cron/backup runs work.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/proton-drive version")
  end
end
