# Auto-generated by proton-drive-cli-brew from Proton's release manifest.
# Do not edit by hand — run `update.sh` (CI keeps it current).
class ProtonDriveCli < Formula
  desc "Access Proton Drive end-to-end encrypted cloud storage from the terminal"
  homepage "https://proton.me/drive"
  version "0.9.0"
  license "MIT"

  # Prebuilt x86_64 Linux bottle so `brew install` pours it with no C compiler
  # (Homebrew-on-Linux otherwise requires one — a problem on atomic distros).
  # macOS and other arches fall back to the direct-from-Proton url below; macOS
  # always has clang via the required Command Line Tools, so no bottle is needed.
  bottle do
    root_url "https://github.com/jakobhviid/proton-drive-cli-brew/releases/download/v0.9.0"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "1cb925ab01939d00168826cd33314034be90537cf5918966c2ae7cb61da2897c"
  end

  on_macos do
    on_arm do
      url "https://proton.me/download/drive/cli/0.9.0/darwin-arm64/proton-drive"
      sha256 "fe329d9d2a55753f515c8a37046767cdf0fbb4a57a894633a61fff9f53696e38"
    end
    on_intel do
      url "https://proton.me/download/drive/cli/0.9.0/darwin-x64/proton-drive"
      sha256 "bf7def0bd8d64ed389f99a6c01f381d744af3a3c65edf9b35c08a6136e1727e2"
    end
  end

  on_linux do
    # On a headless Linux server there's no Secret Service/libsecret keyring, so
    # the session can be stored in `pass` instead (PROTON_DRIVE_CREDENTIALS_STORE
    # — see caveats). Ship it so that path is one env var away, not another install.
    depends_on "pass"

    on_arm do
      url "https://proton.me/download/drive/cli/0.9.0/linux-arm64/proton-drive"
      sha256 "63033ed3bc7d262d074bfd0ec123303112bb9f85d2414c24e8c9f07e6ab27d30"
    end
    on_intel do
      url "https://proton.me/download/drive/cli/0.9.0/linux-x64/proton-drive"
      sha256 "4f66f984b6361084d46567b8f4fd4851f4271eb9f77e5d181e1eff3c8a332501"
    end
  end

  # Proton names the binary `proton-drive`; keep that so their docs' commands
  # work verbatim. The *formula* is proton-drive-cli to avoid the main app's name.
  def install
    bin.install "proton-drive"
  end

  def caveats
    <<~EOS
      proton-drive keeps its login session in your OS keyring — Keychain on macOS,
      Secret Service/libsecret on Linux. A headless Linux server has no keyring, so
      store the session in `pass` (installed as a dependency here) instead:

        gpg --quick-generate-key "proton-drive" default default never
        pass init "proton-drive"
        export PROTON_DRIVE_CREDENTIALS_STORE=pass   # add to your profile / systemd unit

      Sign-in is browser-based, so authenticate once interactively (or on a desktop
      sharing the same pass/GPG key) — then unattended cron/backup runs work.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/proton-drive version")
  end
end
